recherche_task:
  description: >
    Analyser les tendances Motion 2026.
  expected_output: >
    Un rapport technique.
  agent: expert_technique

developpement_task:
  description: >
    Coder un effet Three.js.
  expected_output: >
    Un script fonctionnel.
  agent: designer_motion